import { useState } from "react";

const BRAND = "#6d5df6";

function Stat({ value, label }) {
  return (
    <div className="stat">
      <strong>{value}</strong>
      <span>{label}</span>
    </div>
  );
}

function Todo() {
  const [tasks, setTasks] = useState([
    { id: 1, title: "Explore SuperApp", done: true },
    { id: 2, title: "Add your first task", done: false },
    { id: 3, title: "Toggle dark mode", done: false },
  ]);
  const [text, setText] = useState("");

  function add(e) {
    e.preventDefault();
    const t = text.trim();
    if (!t) return;
    setTasks((prev) => [{ id: Date.now(), title: t, done: false }, ...prev]);
    setText("");
  }

  function toggle(id) {
    setTasks((prev) =>
      prev.map((t) => (t.id === id ? { ...t, done: !t.done } : t))
    );
  }

  function remove(id) {
    setTasks((prev) => prev.filter((t) => t.id !== id));
  }

  const remaining = tasks.filter((t) => !t.done).length;

  return (
    <section className="panel">
      <div className="panel-head">
        <h2>Tasks</h2>
        <span className="pill">{remaining} left</span>
      </div>
      <form onSubmit={add} className="add-row">
        <input
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="What needs to be done?"
        />
        <button type="submit">Add</button>
      </form>
      <ul className="todo-list">
        {tasks.map((t) => (
          <li key={t.id} className={t.done ? "done" : ""}>
            <button
              className="check"
              onClick={() => toggle(t.id)}
              aria-label="Toggle task"
            >
              {t.done ? "✓" : ""}
            </button>
            <span className="title" onClick={() => toggle(t.id)}>
              {t.title}
            </span>
            <button className="x" onClick={() => remove(t.id)} aria-label="Delete">
              ✕
            </button>
          </li>
        ))}
      </ul>
    </section>
  );
}

function Counter() {
  const [count, setCount] = useState(0);
  return (
    <section className="panel">
      <div className="panel-head">
        <h2>Counter</h2>
      </div>
      <p className="muted">React state in action — click the buttons.</p>
      <div className="counter">
        <button onClick={() => setCount((c) => c - 1)} aria-label="Decrement">−</button>
        <span>{count}</span>
        <button onClick={() => setCount((c) => c + 1)} aria-label="Increment">+</button>
      </div>
    </section>
  );
}

export default function App() {
  const [dark, setDark] = useState(false);

  return (
    <div className={"app" + (dark ? " dark" : "")} style={{ "--brand": BRAND }}>
      <header className="nav">
        <div className="container nav-inner">
          <a className="logo" href="#">
            SuperApp
            <span className="dot">.</span>
          </a>
          <button className="theme-btn" onClick={() => setDark((d) => !d)}>
            {dark ? "☀" : "☾"}
          </button>
        </div>
      </header>

      <section className="hero">
        <div className="container">
          <span className="badge">✦ React + Vite</span>
          <h1>
            SuperApp — <span className="accent">An interactive React application</span>
          </h1>
          <p>build me a react app called SuperApp. This page is a real React app built with npm — try it.</p>
        </div>
      </section>

      <main className="container">
        <div className="grid">
          <Todo />
          <Counter />
          <section className="panel">
            <div className="panel-head">
              <h2>Stats</h2>
            </div>
            <div className="stats">
              <Stat value="18" label="Components" />
              <Stat value="100%" label="Your code" />
              <Stat value="5" label="Recipes" />
            </div>
          </section>
        </div>
      </main>

      <footer className="footer">
        <div className="container">
          <span>SuperApp. — generated by Forge</span>
        </div>
      </footer>
    </div>
  );
}
